### ISSUE TITLE
Move navigation elements to the left side

### ISSUE THREAD

**Issue by AkashBhave** [fighting-covid/website#4]
All elements should be moved to the left side. The "Donate PPE" and "Request PPE" links should be condensed into a button titled "Get Involved". I personally think the elements should be in a `container` with a horizontal margin when on desktop.

**Comment by Jklein64** [comment]
Shouldn't we put them on the right side so there isn't a massive empty space there on desktop?

**Comment by AkashBhave** [comment]
Wait so you want move all navigation elements to the right side instead of the left? All this issue is doing is moving the elements to one side so that there isn't a gap in the header, but right-aligning instead of left is a bit unconventional.

**Comment by VarunChilukuri** [comment]
Here are the two options

![image](https://user-images.githubusercontent.com/48163435/80730268-5f518080-8ad7-11ea-975f-f681b6e6bae0.png)
 
![image](https://user-images.githubusercontent.com/48163435/80730359-7c864f00-8ad7-11ea-8aa3-d4e19a50b5ba.png)

I personally think the right-aligning looks better

**Comment by AkashBhave** [comment]
Yeah we're going with right-align, I was confused earlier because I thought Jason meant right-align everything (including the logo), which would've been weird. @VarunChilukuri you should go ahead and commit if you already have the changes.

**Comment by AkashBhave** [comment]
Go ahead, if you could sync dev with master that'd be great too.

**Comment by Jklein64** [comment]
I just condensed the "Request PPE" button and the "Donate PPE" button into a single "Get Involved!" button that reveals the two of them on click, and pushed the change to dev.  What do you think?

**Comment by VarunChilukuri** [comment]
Everything looks good! My only suggestion would be to slightly reduce the height of the button.

**Comment by AkashBhave** [comment]
Great job! In addition to @VarunChilukuri's suggestion, I think it'd be better if the dropdown was activated upon hover instead of click.

**Comment by Jklein64** [comment]
I shortened the button, but using hover is tricky since the menu needs to stay when you hover off of the button, and I can't use `element.getBoundingClientRect()`.
