### ISSUE TITLE
Create make page

### ISSUE THREAD

**Issue by AkashBhave** [fighting-covid/website#6]
Use the `react-stl-viewer` package to display the STL files in an interactive manner. We're still waiting on the files themselves so just use a random open-source one for now. The files should probably be placed under the _assets_ folder.

**Comment by VarunChilukuri** [comment]
Pushed changes to dev. Everything is set up but the actual file won't load when I tested it on localhost.

**Comment by VarunChilukuri** [comment]
![image](https://user-images.githubusercontent.com/48163435/80646858-7fcbfd00-8a3b-11ea-83b9-9c129cd0d3ed.png)
![image](https://user-images.githubusercontent.com/48163435/80646901-940ffa00-8a3b-11ea-8200-64954de48fa2.png)

**Comment by AkashBhave** [comment]
Awesome. I'll be AFK for a bit but will investigate soon.

**Comment by VarunChilukuri** [comment]
We could also try using this: http://github.com/bohdanbirdie/react-stl-obj-viewer

**Comment by VarunChilukuri** [comment]
I just finished adding two STL files to the "Make PPE" page and added it to the navigation bar. I pushed my changes to dev. Lmk what you guys think.
